### ISSUE TITLE
Variable `unicode` is not defined in `PyOpenCV\pygazetracker\generic.py`

### ISSUE THREAD

**Issue by TomZiW** [esdalmaijer/webcam-eyetracker#19]
As title says, the variable `unicode` is not defined in `PyOpenCV\pygazetracker\generic.py`. I am not sure if the user is suppose to replace it or if it is defined somewhere else?

**Comment by esdalmaijer** [comment]
That's the Python 2 function `unicode`. This codebase is so old, it wasn't ever upgraded to Python 3. (Hence the unicode strings too.)

**Comment by TomZiW** [comment]
I see, thank you for your reply! I wanted to try to use this package and PyGaze to figure out web cam eye tracking and gaze estimation. Would you recommend me using something more up to date like openCV-python?
