### ISSUE TITLE
'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by bemoregt** [esdalmaijer/webcam-eyetracker#7]
Hi, @mxgxw @esdalmaijer @jeffesquivels 

I met this error when run example.py.

kraken-2:PyOpenCV dti$ python3 example.py 
Traceback (most recent call last):
  File "example.py", line 9, in <module>
    from pygazetracker.webcam import WebCamTracker
  File "/Users/dti/webcam-eyetracker/PyOpenCV/pygazetracker/__init__.py", line 22, in <module>
    _DIR = os.path.abspath(os.path.dirname(__file__)).decode(u'utf-8')
AttributeError: 'str' object has no attribute 'decode'
kraken-2:PyOpenCV dti$  

What's wrong with me?

Thanks in advance~

**Comment by esdalmaijer** [comment]
You're trying to run a Python 2 script using Python 3. Sorry, I've not had a chance to update to 3 yet, shame on me!
