### ISSUE TITLE
Problems using the OpenCV option

### ISSUE THREAD

**Issue by eviling** [esdalmaijer/webcam-eyetracker#8]
Hello,

I runned the OpenCV example.py on python 2.7. While it said three times: [ INFO:0] Initialize OpenCL runtime... it did not do anything else jut updated the test file.

For what I saw on the website, it should open a windows with the eye tracking, but I do not can make it work.

So, my question is if the code should open a new window as in the video on the PyGaze website or just update the test file.

**Comment by esdalmaijer** [comment]
The website shows the PyGame implementation. The [OpenCV example](https://github.com/esdalmaijer/webcam-eyetracker/blob/master/PyOpenCV/example.py) does not open any windows.
